ci:
  autofix_prs: false
  autoupdate_commit_msg: "pre-commit: bump repositories"

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.1
    hooks:
      - id: ruff
        args: [--fix, --show-fixes]
      - id: ruff-format
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        args: [-L, sur]
