baseURL = 'https://lains.space/'
languageCode = 'en-us'
title = 'Filipe Laíns'
theme='ffy00'
copyright = '© Filipe Laíns'
pygmentsstyle = 'monokai'
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
mode='auto'
featherIconsCDN = true

[[params.social]]
name = 'GitHub'
icon = 'github'
url = 'https://github.com/FFY00'

[[params.social]]
name = 'GitLab'
icon = 'gitlab'
url = 'https://gitlab.com/FFY00'

[[params.social]]
name = 'Linkedin'
icon = 'linkedin'
url = 'https://www.linkedin.com/in/lains'

[[menu.main]]
name = 'Home'
url = '/'
weight = 1

[[menu.main]]
name = 'Blog'
url = '/posts'
weight = 2

